[connections.default]
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "MCEDKTD.GF62682"
user = "jdixson27"
password = "KorbinMyles230952911!"
